title: "Cheng Yu (Eric) Wu - Data Science Resume"
description: "Data scientist showcasing projects, skills, and experience."
baseurl: ""
url: "https://yourusername.github.io"
logo: "/assets/images/logo.png"  # Path to your logo file
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
collections:
  projects:
    output: true
    permalink: /projects/:path/
  experience:
    output: true
    permalink: /experience/:path/
  education:
    output: true
    permalink: /education/:path/
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
