title: Cheng Yu (Eric) Wu
#logo: /assets/img/headshot_circle.png
description: A showcase of my data science projects and skills.
theme: jekyll-theme-minimal
highlighter: rouge
markdown: kramdown
show_downloads: true
theme: jekyll-theme-minimal
