title: Your Name
description: >-
  A personal portfolio showcasing my skills, experience, and projects.
baseurl: "/your-portfolio" # Change to your repository name for project sites, e.g., /example-portfolio
url: "[invalid url, do not cite] # Set to your GitHub Pages URL
show_downloads: false
google_analytics: # Optional: Add your Google Analytics tracking ID
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
