title: Your Name
description: >-
  A personal portfolio showcasing my skills, experience, and projects.
baseurl: "/your-portfolio"
url: "https://yourusername.github.io"
show_downloads: false
google_analytics:
theme: minima
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
